'use strict';

// Self-contained HTML insights report for a dataset — downloadable, shareable,
// opens in any browser with no dependencies.

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function buildReport(dataset) {
  const p = dataset.profile;
  const scoreColor = p.quality.score >= 80 ? '#1a9e5c' : p.quality.score >= 55 ? '#e8930c' : '#d64550';

  const columnRows = p.columns.map((c) => {
    const stats = c.mean !== undefined
      ? `mean ${c.mean} · median ${c.median} · σ ${c.stddev} · [${c.min} … ${c.max}]`
      : c.topValues && c.topValues.length
        ? `top: ${c.topValues.slice(0, 3).map((t) => `${esc(t.value)} (${t.count})`).join(', ')}`
        : c.dateMin ? `${c.dateMin} → ${c.dateMax}` : '—';
    const flags = (c.flags || []).map((f) => `<span class="flag">⚠ ${esc(f)}</span>`).join(' ');
    return `<tr><td><strong>${esc(c.name)}</strong></td><td>${c.type}</td><td>${c.nullPct}%</td><td>${c.distinct}</td><td>${stats} ${flags}</td></tr>`;
  }).join('\n');

  const anomalyRows = p.anomalies.slice(0, 15).map((a) =>
    `<tr><td>${esc(a.column)}</td><td>${a.row}</td><td>${a.value}</td><td>${a.zScore}</td><td>${a.method}</td></tr>`).join('\n');

  const corrRows = p.correlations.slice(0, 8).map((c) =>
    `<tr><td>${esc(c.col1)} × ${esc(c.col2)}</td><td>${c.r}</td><td>${c.n}</td></tr>`).join('\n');

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>DataScope report — ${esc(dataset.name)}</title>
<style>
  body { font-family: 'Segoe UI', system-ui, sans-serif; color: #2b2333; max-width: 860px; margin: 32px auto; padding: 0 20px; }
  h1 { font-size: 22px; } h2 { font-size: 16px; margin-top: 28px; border-bottom: 2px solid #f43397; padding-bottom: 4px; }
  .muted { color: #8a8095; } .score { font-size: 44px; font-weight: 800; color: ${scoreColor}; }
  table { border-collapse: collapse; width: 100%; font-size: 13px; margin-top: 10px; }
  th { text-align: left; color: #8a8095; padding: 6px 10px 6px 0; border-bottom: 1px solid #e7e2ee; }
  td { padding: 6px 10px 6px 0; border-bottom: 1px solid #f3eff7; vertical-align: top; }
  ul { line-height: 1.7; }
  .flag { background: #fff7e8; color: #9a6206; border-radius: 6px; padding: 1px 7px; font-size: 11.5px; white-space: nowrap; }
  .ded { color: #d64550; font-weight: 700; }
  footer { margin-top: 36px; color: #8a8095; font-size: 12px; border-top: 1px solid #e7e2ee; padding-top: 10px; }
</style></head><body>
<h1>🔬 DataScope report — ${esc(dataset.name)}</h1>
<p class="muted">${dataset.rowCount} rows · ${dataset.columnCount} columns · generated ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC</p>

<h2>Data quality</h2>
<p><span class="score">${p.quality.score}</span> / 100</p>
${p.quality.deductions.length ? `<ul>${p.quality.deductions.map((d) => `<li><span class="ded">−${d.points}</span> ${esc(d.reason)}</li>`).join('')}</ul>` : '<p>No quality issues detected.</p>'}

<h2>Auto-insights</h2>
<ul>${p.insights.map((s) => `<li>${esc(s)}</li>`).join('')}</ul>

<h2>Columns</h2>
<table><tr><th>Column</th><th>Type</th><th>Null</th><th>Distinct</th><th>Summary</th></tr>
${columnRows}</table>

${p.anomalies.length ? `<h2>Anomalies (top ${Math.min(15, p.anomalies.length)} of ${p.anomalies.length})</h2>
<table><tr><th>Column</th><th>Row</th><th>Value</th><th>z-score</th><th>Method</th></tr>${anomalyRows}</table>` : ''}

${p.correlations.length ? `<h2>Correlations</h2>
<table><tr><th>Pair</th><th>Pearson r</th><th>n</th></tr>${corrRows}</table>` : ''}

<footer>Generated by DataScope — statistics computed deterministically in the backend; no raw data leaves your machine.</footer>
</body></html>`;
}

module.exports = { buildReport };
